<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DexManager.AdbProxy</RootNamespace>
    <AssemblyName>DXMAdbProxy</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\FileTransferProtocol.cs">
      <Link>Shared\FileTransferProtocol.cs</Link>
    </Compile>
  </ItemGroup>

</Project>
